version: '2'
services:

  iridiumd1:
    image: iridium:test2
    entrypoint: /iridium/iridiumd
    command: ["--testnet", "--data-dir", "/data", "--rpc-bind-ip", "0.0.0.0"]

  iridiumd2:
    image: iridium:test2
    entrypoint: /iridium/iridiumd
    command: ["--testnet", "--data-dir", "/data", "--rpc-bind-ip", "0.0.0.0", "--add-peer", "iridiumd1:12007"]
    links:
      - iridiumd1

  walletd-gen:
    image: iridium:test2
    entrypoint: /iridium/iridium_walletd
    command: ["--testnet", "--data-dir", "/data", "-w", "/data/wallet", "-p", "password", "-g"]
    volumes:
      - wallet-volume:/data

  walletd:
    image: iridium:test2
    entrypoint: /iridium/iridium_walletd
    command: ["--testnet", "--data-dir", "/data", "-w", "/data/wallet", "-p", "password", "--daemon-address", "iridiumd2", "--log-level", "2"]
    volumes:
      - wallet-volume:/data
    links:
      - walletd-gen
      - iridiumd2
    ports:
      - 14008:14007

  miner:
    image: iridium:test2
    entrypoint: /iridium/iridium_miner
    command: ["--address", "ir2fq8BaEgdCoWprKm8i9c3tk5UURqir4PWw28mT6Re3V7u9HNNotXNU9JJ7kHT5yKdTxcd7JHJEthVdm7eho7vW1CWa8bAL4", "--daemon-host", "iridiumd2", "--threads", "1", "--limit", "25"]
    links:
      - iridiumd2


volumes:
  wallet-volume: