version: '2'
services:

  iridiumd1:
    image: danielclasen/iridium-core
    entrypoint: /iridium/iridiumd
    command: ["--testnet", "--data-dir", "/data", "--rpc-bind-ip", "0.0.0.0"]


  iridiumd2:
    image: danielclasen/iridium-core
    entrypoint: /iridium/iridiumd
    command: ["--testnet", "--data-dir", "/data", "--rpc-bind-ip", "0.0.0.0", "--add-peer", "iridiumd1:12007"]
    links:
      - iridiumd1


  walletd-gen1:
    image: danielclasen/iridium-walletd-gen
    command: ["--testnet", "--data-dir", "/data", "-w", "/data/wallet", "-p", "password", "-g"]
    volumes:
      - ./src/test/resources/iridium/wallet1:/data


  walletd1:
    image: danielclasen/iridium-core
    entrypoint: /iridium/iridium_walletd
    command: ["--testnet", "--data-dir", "/data", "-w", "/data/wallet", "-p", "password", "--daemon-address", "iridiumd2", "--log-level", "2"]
    volumes:
      - ./src/test/resources/iridium/wallet1:/data
    links:
      - walletd-gen1
      - iridiumd2
    ports:
      - 14008:14007


  miner:
    image: danielclasen/iridium-testminer
    command: ["--daemon-host", "iridiumd2", "--threads", "1", "--limit", "25"]
    links:
      - iridiumd2
    volumes:
      - ./src/test/resources/iridium/wallet1:/data


  walletd-gen2:
    image: danielclasen/iridium-walletd-gen
    command: ["--testnet", "--data-dir", "/data", "-w", "/data/wallet", "-p", "password", "-g"]
    volumes:
      - ./src/test/resources/iridium/wallet2:/data

  walletd2:
    image: danielclasen/iridium-core
    entrypoint: /iridium/iridium_walletd
    command: ["--testnet", "--data-dir", "/data", "-w", "/data/wallet", "-p", "password", "--daemon-address", "iridiumd1", "--log-level", "2"]
    volumes:
      - ./src/test/resources/iridium/wallet2:/data
    links:
      - walletd-gen2
      - iridiumd1
    ports:
      - 14009:14007

